import { defineTours } from "../tour";
import { getTourReady } from "../shared/tourReadiness";

export const appTours = defineTours({
  "all-features": [
    {
      id: "home.start",
      target: "home.startButton",
      title: "Welcome",
      description: "Entry step on home with prompt and named tour registry.",
      route: "/",
      placement: "bottom",
    },
    {
      id: "home.storage",
      target: "home.storageCard",
      title: "Storage + Seen State",
      description: "This validates persistence helpers and seen markers.",
      route: "/",
      placement: "bottom",
    },
    {
      id: "home.registry",
      target: "home.registryCard",
      title: "Registry Helpers",
      description: "Uses hasTour/getTour for discoverability and debug checks.",
      route: "/",
      placement: "bottom",
    },
    {
      id: "home.item.12",
      target: "home.item.12",
      title: "ScrollView Deep Reveal",
      description: "Auto-scrolls down to a deep target in ScrollView.",
      route: "/",
      scrollToTarget: true,
      scrollContainerId: "home-scroll",
      placement: "top",
    },
    {
      id: "home.item.4",
      target: "home.item.4",
      title: "ScrollView Upward Reveal",
      description: "Auto-scrolls upward to a previously passed target.",
      route: "/",
      scrollToTarget: true,
      scrollContainerId: "home-scroll",
      placement: "top",
    },
    {
      id: "flat.item.17",
      target: "flat.item.17",
      title: "FlatList Reveal",
      description: "Cross-route navigation then FlatList target reveal.",
      route: "/flat",
      scrollToTarget: true,
      scrollContainerId: "flat-container",
      placement: "top",
    },
    {
      id: "flat.item.3",
      target: "flat.item.3",
      title: "FlatList Upward",
      description: "Moves upward to verify reverse list scrolling.",
      route: "/flat",
      scrollToTarget: true,
      scrollContainerId: "flat-container",
      placement: "bottom",
    },
    {
      id: "section.deep",
      target: "section.1.item.7",
      title: "SectionList Deep",
      description: "SectionList reveal using section/item mapping.",
      route: "/section",
      scrollToTarget: true,
      scrollContainerId: "section-container",
      placement: "top",
    },
    {
      id: "section.near",
      target: "section.0.item.2",
      title: "SectionList Upward",
      description: "Reverse reveal to earlier section item.",
      route: "/section",
      scrollToTarget: true,
      scrollContainerId: "section-container",
      placement: "bottom",
    },
    {
      id: "lab.start",
      target: "lab.start",
      title: "Nested Stack Start",
      description: "Testing tab + nested stack routing behavior.",
      route: "/lab",
      placement: "bottom",
    },
    {
      id: "lab.details",
      target: "lab.details.cta",
      title: "Readiness Gate",
      description: "Waits for async readiness before target appears.",
      route: "/lab/details",
      readiness: {
        timeoutMs: 10000,
        isReady: () => getTourReady("lab.details.ready"),
      },
      placement: "top",
    },
    {
      id: "settings.toggle",
      target: "settings.toggle",
      title: "Target Interaction",
      description: "Try toggling switch while step is active.",
      route: "/settings",
      allowInteractionWithTarget: true,
      placement: "bottom",
    },
    {
      id: "settings.advanced",
      target: "settings.advancedCta",
      title: "Replace Navigation",
      description: "Navigates to nested settings route and highlights CTA.",
      route: "/settings/advanced",
      navigationMode: "replace",
      placement: "top",
    },
  ],

  "quick-check": [
    {
      id: "quick.home",
      target: "home.startButton",
      title: "Quick Check",
      description: "A minimal smoke test without prompt.",
      route: "/",
      placement: "bottom",
    },
    {
      id: "quick.linkRow",
      target: "home.linkRow",
      title: "Navigation Links",
      description: "Confirms target registration and tooltip rendering.",
      route: "/",
      scrollToTarget: true,
      scrollContainerId: "home-scroll",
      placement: "top",
    },
  ],

  "flatlist-only": [
    {
      id: "flat.3",
      target: "flat.item.3",
      title: "Near Item",
      description: "Starts near top for baseline measurement.",
      route: "/flat",
    },
    {
      id: "flat.24",
      target: "flat.item.24",
      title: "Deep Item",
      description: "Downward reveal for FlatList.",
      route: "/flat",
      scrollToTarget: true,
      scrollContainerId: "flat-container",
    },
    {
      id: "flat.17",
      target: "flat.item.17",
      title: "Upward Item",
      description: "Upward reveal for FlatList.",
      route: "/flat",
      scrollToTarget: true,
      scrollContainerId: "flat-container",
    },
  ],

  "sectionlist-only": [
    {
      id: "section.0.2",
      target: "section.0.item.2",
      title: "Start Section",
      description: "Near target in first section.",
      route: "/section",
    },
    {
      id: "section.1.7",
      target: "section.1.item.7",
      title: "Deep Section Target",
      description: "Downward reveal in next section.",
      route: "/section",
      scrollToTarget: true,
      scrollContainerId: "section-container",
    },
    {
      id: "section.0.2b",
      target: "section.0.item.2",
      title: "Back Up",
      description: "Upward correction test for SectionList.",
      route: "/section",
      scrollToTarget: true,
      scrollContainerId: "section-container",
    },
  ],

  "nested-lab": [
    {
      id: "lab.start.short",
      target: "lab.start",
      title: "Lab Intro",
      route: "/lab",
      description: "Nested stack starting point.",
    },
    {
      id: "lab.details.short",
      target: "lab.details.cta",
      title: "Lab Details",
      route: "/lab/details",
      readiness: {
        timeoutMs: 10000,
        isReady: () => getTourReady("lab.details.ready"),
      },
      description: "Waits for delayed readiness before CTA target.",
    },
  ],

  "settings-only": [
    {
      id: "settings.start",
      target: "settings.start",
      title: "Settings Flow",
      description: "Starts at settings root.",
      route: "/settings",
    },
    {
      id: "settings.toggle.short",
      target: "settings.toggle",
      title: "Interactive Target",
      description: "Interaction with target should remain enabled.",
      route: "/settings",
      allowInteractionWithTarget: true,
    },
    {
      id: "settings.advanced.short",
      target: "settings.advancedCta",
      title: "Advanced Route",
      description: "Route change to nested advanced screen.",
      route: "/settings/advanced",
      navigationMode: "replace",
    },
  ],
});
