import { defineTours } from "../tour";

export const appTours = defineTours({
  dashboard: [
    {
      id: "home.start",
      target: "home.startButton",
      title: "Welcome",
      description: "Start here whenever you want a quick walkthrough of the product screens.",
      placement: "bottom",
      route: "/",
    },
    {
      id: "home.stats",
      target: "home.statsCard",
      title: "Live Snapshot",
      description: "This card shows current performance and status at a glance.",
      placement: "bottom",
      route: "/",
    },
    {
      id: "details.cta",
      target: "details.primaryCta",
      title: "Cross-screen Tour",
      description: "The tour moves to Details and waits until the action is available.",
      placement: "top",
      route: "/details",
      readiness: { timeoutMs: 8000 },
    },
    {
      id: "home.item6",
      target: "home.item.6",
      title: "Scrolled Item 6",
      description: "This step auto-scrolls to reveal item 6 in the dashboard list.",
      placement: "top",
      route: "/",
      scrollToTarget: true,
      scrollContainerId: "home-scroll",
    },
    {
      id: "home.item10",
      target: "home.item.10",
      title: "Scrolled Item 10",
      description: "This step auto-scrolls to reveal item 10 in the dashboard list.",
      placement: "top",
      route: "/",
      scrollToTarget: true,
      scrollContainerId: "home-scroll",
    },
    {
      id: "home.item14",
      target: "home.item.14",
      title: "Scrolled Item 14",
      description: "This step auto-scrolls to reveal item 14 in the dashboard list.",
      placement: "top",
      route: "/",
      scrollToTarget: true,
      scrollContainerId: "home-scroll",
    },
    {
      id: "profile.cta",
      target: "profile.cta",
      title: "Profile Screen",
      description: "Tours can target any screen, like this one on Profile.",
      placement: "bottom",
      route: "/profile",
    },
    {
      id: "flat.item10",
      target: "flat.item.10",
      title: "FlatList Support",
      description: "This step demonstrates FlatList auto-scroll reveal support.",
      placement: "top",
      route: "/flatlist",
      scrollToTarget: true,
      scrollContainerId: "flatlist-container",
    },
    {
      id: "section.deep",
      target: "section.1.item.6",
      title: "SectionList Support",
      description: "This step demonstrates SectionList section/item auto-scroll support.",
      placement: "top",
      route: "/sectionlist",
      scrollToTarget: true,
      scrollContainerId: "sectionlist-container",
    },
  ],
  flatlist: [
    {
      id: "flat.start",
      target: "flat.item.2",
      title: "FlatList Start",
      description: "We begin near the top of the list.",
      route: "/flatlist",
    },
    {
      id: "flat.item.10",
      target: "flat.item.10",
      title: "Auto-scroll to 10",
      description: "This step uses container-based reveal for FlatList.",
      route: "/flatlist",
      scrollToTarget: true,
      scrollContainerId: "flatlist-container",
    },
    {
      id: "flat.item.14",
      target: "flat.item.14",
      title: "Auto-scroll to 14",
      description: "A second deep target in the same list.",
      route: "/flatlist",
      scrollToTarget: true,
      scrollContainerId: "flatlist-container",
    },
  ],
  sectionlist: [
    {
      id: "section.start",
      target: "section.0.item.2",
      title: "SectionList Start",
      description: "We begin near the top section.",
      route: "/sectionlist",
    },
    {
      id: "section.deep",
      target: "section.1.item.6",
      title: "Jump to Section Item",
      description: "This step scrolls to section 2 item 6.",
      route: "/sectionlist",
      scrollToTarget: true,
      scrollContainerId: "sectionlist-container",
    },
  ],
});
